# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Science and its Applications
author: jckantor
logo: media/MaxPixel.net-Sky-Constellation-Map-Constellation-Zodiac-Sign-3301739.jpg
exclude_patterns: [README.md, .DS_Store, "**.ipynb_checkpoints", "**.pytest_cache"]

# Launch on Google Colab button
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  
# MyST syntax extensions
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - amsmath

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: cetus-ds.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jckantor/cetus-ds  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

